//Textos
char* palabras[CANTIDAD_LETRAS]={"arreglo", "byte", "compilador", "double", "estrutura", "float",
 "gigabyte", "hardware", "int", "java", "kilobyte", "lag", "malware", "navegador",
  "octal", "password", "qwerty", "ram", "stack", "teclado", "ubuntu", "variable", "web", "x", "youtube", "zip"};

char* descripciones[CANTIDAD_LETRAS]={"Coleccion de elementos del mismo tipo ordenados de manera secuencial\n", 
"Unidad de informacion compuesta generalmente de 8 bits\n",
"Que compila\n",
"Declaracion flotante de presicion doble\n",
"Agrupacion de datos de diferente tipo\n",
"Numero de punto flotante\n",
"Conjunto de 1024 MB\n",
"Las partes fisicas de un ordenador\n",
"Declaracion de numero entero\n",
"Lenguaje de programacion orientado a objetos\n",
"Conjunto de 1024 bytes\n",
"Retraso de informacion\n",
"Programa malulo uwu\n",
"Programa para visualizar paginas web\n",
"Sistema de enumeracon de base 8\n",
"Metodo de seguridad para identificar a un usuario\n",
"Disposicion del teclado mas usual en celulares y coputadores\n",
"Memoria de acceso aleatorio\n",
"Estructura de datos usada para almacenar objetos\n",
"Dispositivo de entrada de datos al computador\n",
"Distribucion de linux\n",
"Estructura de programacion que contiene datos\n",
"Se conoce como World Wide Web\n",
"Indicador de extendido\n",
"Sitio web que permite compartir videos\n",
"Archivo comprimido\n"};